name: popup_menu_title
description: A PopupMenuEntry implementation to show a title.
version: 1.1.0-nullsafety.1
homepage: https://github.com/hacker1024/popup_menu_title

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.24.0-10.2.pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3