name: popup_menu_title
description: A PopupMenuEntry implementation to show a title.
version: 1.0.0-nullsafety.2
homepage: https://github.com/hacker1024/popup_menu_title

environment:
  sdk: ">=2.11.0-260.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.2